### ISSUE TITLE
Strange input signal behavior

### ISSUE THREAD

**Issue by chykon** [intel/rohd#158]
## Describe the bug
The incoming signal behaves incorrectly in a certain case. Adding a useless assignment operator solves the problem.

## To Reproduce
1. [Get project](https://github.com/chykon/utf8encoder-hw/tree/3183a97e957b93e069dd9b10644ab057a2a434eb)
2. Go to [file](https://github.com/chykon/utf8encoder-hw/blob/3183a97e957b93e069dd9b10644ab057a2a434eb/lib/src/utf8encoder.dart#L53) and comment highlighted line
3. Run [another file](https://github.com/chykon/utf8encoder-hw/blob/3183a97e957b93e069dd9b10644ab057a2a434eb/example/lib/another.dart)

## Expected behavior
The "codepoint" input does not require the use of a useless assignment operator to work correctly.

## Actual behavior
The "codepoint" input does not work correctly.

## Additional details
```
Dart SDK version: 2.18.0 (stable) (Fri Aug 26 10:22:54 2022 +0000) on "linux_x64"
```
```yaml
name: utf8encoder_hw
version: 0.1.0-prototype.1
description: A hardware UTF-8 encoder written in Dart using the ROHD framework.
repository: https://github.com/chykon/utf8encoder-hw
issue_tracker: https://github.com/chykon/utf8encoder-hw/issues

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  rohd: ^0.3.2

dev_dependencies:
  test: ^1.21.5
  very_good_analysis: ^3.0.1
```

**Additional context**
To me, this is some weird issue that occurs with code point U+2020 but does not occur with U+2019 and U+2021. I also want to note that I encountered a problem when testing using this [file](https://www.cl.cam.ac.uk/~mgk25/ucs/examples/UTF-8-demo.txt). Before the appearance of the U+2020 code point, there are many other three-byte sequences in the file, but there are no problems with them.
