### ISSUE TITLE
Simulation Bug: WaveDumper Function Must Be Placed Before Simulator Class to Prevent Errors

### ISSUE THREAD

**Issue by quekyj** [intel/rohd#446]
### Describe the bug

During simulation, the function `WaveDumper` need to be place before any of the `Simulator` class else its going to throw the bug as shown below:

![image](https://github.com/intel/rohd/assets/115072593/88e6813d-5c7f-4c7c-b465-a7cc93f4669c)

### To Reproduce

Create a `Simulator` and slot in the `WaveDumper` in the middle of Simulation.

### Expected behavior

It should either: 
1. Throw exception to user to indicate the misplacement of the WaveDumper class.
2. Allow the WaveDumper to be place in any of the location.

### Actual behavior

As of now, no error indicate the misplacement.

### Additional: Dart SDK info

Dart SDK version: 3.3.0-16.0.dev (dev) (Wed Oct 11 21:04:42 2023 -0700) on "windows_x64"

### Additional: pubspec.yaml

```yaml
name: cache
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  rohd: ^0.5.0
  rohd_vf: ^0.5.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
```
