### ISSUE TITLE
[Uncertain]Incorrect behavior of non-blocking assignment in simulation result

### ISSUE THREAD

**Issue by wswongat** [intel/rohd#79]
## Describe the bug
The waveform generated by the ROHD simulator doesn't have same behavior like other simulators such as modelsim.
I need some helps to clarify this bug.

## To Reproduce
Full dart code file
[delay_signal.txt](https://github.com/intel/rohd/files/7970990/delay_signal.txt)
Please change the file extension to dart.
**Core part:**
```
    List<Logic> _z = List<Logic>.generate(depth, (index) => Logic(width: bitWidth));

    var out = addOutput('out', width: bitWidth);

    List<ConditionalAssign> _zList = [_z[0] < inputVal];
    for(int i = 0; i<_z.length;i++){
    // for(int i = _z.length-1; i>=0;i--){
      if(i == _z.length-1){
        _zList.add(out < _z[i]);
      }else{
        _zList.add(_z[i+1] < _z[i]);
      }
    }

    Sequential(clk, [
      IfBlock([
        Iff(en, _zList
        ),
        Else([
          out < 0,
        ])
      ])
    ]);
  }
```

1. Run a simulation with ROHD
2. See the waveform from gtkwave

## Expected behavior
The input value should be appeared in the out value after few clock cycles.

Generated systemverilog:
```
//  sequential
always_ff @(posedge clk) begin
  if(en) begin
      s0 <= inputVal;
      s1 <= s0;
      s2 <= s1;
      s3 <= s2;
      s4 <= s3;
      out <= s4;
  end   else begin
      out <= 0;
  end 
end
```
modelsim/others result: **<- Correct result**
![image](https://user-images.githubusercontent.com/27878101/151803497-7e0a85ca-5262-47bd-807d-c2d0bcb5bb40.png)
ROHD result:
![image](https://user-images.githubusercontent.com/27878101/151803668-626f1fed-085d-44a3-bc44-3a9904c129a5.png)

## Actual behavior
The out value directly equal to the input val at the first positive edge.

## Additional details
**Please paste the output of `dart --version`**  
```
> dart --version
Dart SDK version: 2.15.1 (stable) (Unknown timestamp) on "linux_x64"
```

**Please paste the contents of your pubspec.yaml file and identify the version of ROHD you're using**  
```yaml
name: delay_signal
description: A simple command-line application.
version: 1.0.0

environment:
  sdk: '>=2.14.3 <3.0.0'


# dependencies:
#   path: ^1.8.0
dependencies:
  rohd:
    git:
      url: https://github.com/intel/rohd.git
      ref: main


dev_dependencies:
  lints: ^1.0.0
```
